name: debugger-hs
version: 0.1.0.0
github: "luc-tielen/debugger-hs"
license: BSD3
author: "Luc Tielen"
maintainer: "luc.tielen@gmail.com"
copyright: "Luc Tielen, 2021"
category: debugging
synopsis: Write your GDB scripts in Haskell.

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/luc-tielen/debugger-hs#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall

default-extensions:
  - DerivingVia
  - LambdaCase
  - OverloadedStrings
  - FlexibleContexts
  - FlexibleInstances

library:
  source-dirs: src
  dependencies:
    - text == 1.*
    - mtl == 2.*
    - dlist == 1.*

tests:
  debugger-hs-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec >= 2.6.1 && < 3.0.0
      - text == 1.*
      - mtl == 2.*
      - neat-interpolation == 0.*
      - debugger-hs
